// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8cP6elbvnfVkak6Gau8sh9Fqmy0ttOFc',
    appId: '1:261142238885:web:4111ed797cd2f9b24c1f4c',
    messagingSenderId: '261142238885',
    projectId: 'tabacco-fda3c',
    authDomain: 'tabacco-fda3c.firebaseapp.com',
    storageBucket: 'tabacco-fda3c.firebasestorage.app',
    measurementId: 'G-7Y24XYFMXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrA39v_-i1QJ2-u1ihv2IpTpU0RqG22Sg',
    appId: '1:261142238885:android:9516110c816b7b0a4c1f4c',
    messagingSenderId: '261142238885',
    projectId: 'tabacco-fda3c',
    storageBucket: 'tabacco-fda3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC29nvxEklf7jI53cpQyQr4AMFm1VQXFg0',
    appId: '1:261142238885:ios:9ab2f51ef3ded9834c1f4c',
    messagingSenderId: '261142238885',
    projectId: 'tabacco-fda3c',
    storageBucket: 'tabacco-fda3c.firebasestorage.app',
    androidClientId: '261142238885-q4simcng19upspchr9ifegbcf9sngbh8.apps.googleusercontent.com',
    iosClientId: '261142238885-7od88ebq39deiu0t03h39viqbc75ck34.apps.googleusercontent.com',
    iosBundleId: 'com.example.auctionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC29nvxEklf7jI53cpQyQr4AMFm1VQXFg0',
    appId: '1:261142238885:ios:9ab2f51ef3ded9834c1f4c',
    messagingSenderId: '261142238885',
    projectId: 'tabacco-fda3c',
    storageBucket: 'tabacco-fda3c.firebasestorage.app',
    androidClientId: '261142238885-q4simcng19upspchr9ifegbcf9sngbh8.apps.googleusercontent.com',
    iosClientId: '261142238885-7od88ebq39deiu0t03h39viqbc75ck34.apps.googleusercontent.com',
    iosBundleId: 'com.example.auctionapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8cP6elbvnfVkak6Gau8sh9Fqmy0ttOFc',
    appId: '1:261142238885:web:e4ba62a79a52d1924c1f4c',
    messagingSenderId: '261142238885',
    projectId: 'tabacco-fda3c',
    authDomain: 'tabacco-fda3c.firebaseapp.com',
    storageBucket: 'tabacco-fda3c.firebasestorage.app',
    measurementId: 'G-K0WQSPLTGK',
  );

}